<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/virifortissimi/image/upload/v1554385010/IMG_20181101_125518.png" alt="Gabriel Emmanuel">
                        <h6>Gabriel Emmanuel</h6>
                        <p>Front-end Enginner</p>
                        <ul class="list">
                           <li><a href="https://www.twitter.com/eghosa_gabriel" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://www.github.com/virifortissimi" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@eghosagabriel" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I'm a techie and a tech enthusiast, a web developer living in Lagos, Nigeria. I am a fan of programming, photography, and technology. I'm also interested in web development and football. You can view my repo <a href="https://www.github.com/virifortissimi" target="_blank">here.</a></p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | Html/Css | Bootstrap</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
